In [3]:
#iris dataset for imgae details length width leaf
#dataset target
#0-setsos
#1-versicolor
#2-verginica
#no encoding
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [6]:


# Load the dataset
iris = load_iris()

# Features (Length/Width of sepals and petals)
X = iris.data

# Target labels (The species: Setosa, Versicolor, or Virginica)
y = iris.target

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
model = DecisionTreeClassifier(
    max_depth=3,           # Limit tree depth
    min_samples_split=5,    # Minimum samples required to split a node
    criterion='gini',       # Measuring the quality of a split
    random_state=42
)

In [11]:
#train model
model.fit(X_train,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,3
,min_samples_split,5
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [12]:
#prediction
y_pred = model.predict(X_test)

In [13]:
#evalution
# 1. Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# 2. Confusion Matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 3. Classification Report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 1.0

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [16]:
# Features: [Sepal Length, Sepal Width, Petal Length, Petal Width]
new_flower = np.array([[6.1, 3.5, 1.4, 0.2]]) 

# Predict the integer class
prediction = model.predict(new_flower)

# Map the integer to the actual name
flower_name = iris.target_names[prediction][0]

print("Predicted flower species:", flower_name)

Predicted flower species: setosa


In [19]:

# OPTION 1: Likely a Setosa (Small petals)
#new_flower = np.array([[5.1, 3.5, 1.4, 0.2]]) 

# OPTION 2: Likely a Versicolor (Medium petals)
new_flower = np.array([[6.0, 3.0, 4.5, 1.5]]) 

# OPTION 3: Likely a Virginica (Large petals)
# new_flower = np.array([[7.2, 3.2, 6.0, 2.5]]) 

# Predict and Print
prediction = model.predict(new_flower)
flower_name = iris.target_names[prediction][0]

print(f"Measurements: {new_flower[0]}")
print(f"Predicted species: {flower_name}")

Measurements: [6.  3.  4.5 1.5]
Predicted species: versicolor
